<?php

use alertCoingecko\Crawler;
use Maknz\Slack\Client as SlackClient;
use Maknz\Slack\Message;


require_once __DIR__ . '/vendor/autoload.php';

header("Content-Type: text/plain");
$list = [
    "https://www.coingecko.com/de/munze/fibswap-dex                        ",
    "https://www.coingecko.com/de/munze/ariva                                   ",
    "https://www.coingecko.com/de/munze/fortube                                 ",
    "https://www.coingecko.com/de/munze/everest                                 ",
    "https://www.coingecko.com/de/munze/marketmove                              ",
    "https://www.coingecko.com/de/munze/meter-governance                        ",
    "https://www.coingecko.com/de/munze/offshift                                ",
    "https://www.coingecko.com/de/munze/lazio-fan-token                         ",
    "https://www.coingecko.com/en/coins/o3-swap                                 ",
    "https://www.coingecko.com/en/coins/bomber-coin                             ",
    "https://www.coingecko.com/en/coins/quidd                                   ",
    "https://www.coingecko.com/en/coins/goal-token                              ",
    "https://www.coingecko.com/en/coins/liquidus                                ",
    "https://www.coingecko.com/en/coins/plastiks                                ",
    "https://www.coingecko.com/en/coins/rewards-bunny                           ",
    "https://www.coingecko.com/en/coins/katana-inu                              ",
    "https://www.coingecko.com/en/coins/jumptoken                               ",
    "https://www.coingecko.com/en/coins/onino                                   ",
    "https://www.coingecko.com/en/coins/defi-warrior                            ",
    "https://www.coingecko.com/en/coins/revolve-games                           ",
    "https://www.coingecko.com/en/coins/pulsepad                                ",
    "https://www.coingecko.com/en/coins/citadel-one                             ",
    "https://www.coingecko.com/en/coins/roseon-finance                          ",
    "https://www.coingecko.com/en/coins/anchorswap                              ",
    "https://www.coingecko.com/en/coins/jetfuel-finance                         ",
    "https://www.coingecko.com/en/coins/growth-defi                             ",
    "https://www.coingecko.com/en/coins/yel-finance                             ",
    "https://www.coingecko.com/en/coins/nabox                                   ",
    "https://www.coingecko.com/en/coins/league-of-ancients                      ",
    "https://www.coingecko.com/en/coins/acryptos                                ",
    "https://www.coingecko.com/en/coins/ok-lets-go                              ",
    "https://www.coingecko.com/en/coins/xtblock-token                           ",
    "https://www.coingecko.com/en/coins/hyve                                    ",
    "https://www.coingecko.com/en/coins/ripio-credit-network                    ",
    "https://www.coingecko.com/en/coins/niob                                    ",
    "https://www.coingecko.com/en/coins/zodium                                  ",
    "https://www.coingecko.com/en/coins/idena                                   ",
    "https://www.coingecko.com/en/coins/astroswap                               ",
    "https://www.coingecko.com/en/coins/hodl-finance                            ",
    "https://www.coingecko.com/en/coins/mist                                    ",
    "https://www.coingecko.com/en/coins/kainet                                  ",
    "https://www.coingecko.com/en/coins/feeder-finance                          ",
    "https://www.coingecko.com/en/coins/metagods                                ",
    "https://www.coingecko.com/en/coins/filecoin-standard-full-hashrate         ",
    "https://www.coingecko.com/en/coins/coinxpad                                ",
    "https://www.coingecko.com/en/coins/ring                                    ",
    "https://www.coingecko.com/en/coins/gami-world                              ",
    "https://www.coingecko.com/en/coins/fastswap-bsc                            ",
    "https://www.coingecko.com/en/coins/bismuth                                 ",
    "https://www.coingecko.com/en/coins/april                                   ",
    "https://www.coingecko.com/en/coins/metastrike                              ",
    "https://www.coingecko.com/en/coins/legend-of-fantasy-war                   ",
    "https://www.coingecko.com/en/coins/elvantis                                ",
    "https://www.coingecko.com/en/coins/revenue-coin                            ",
    "https://www.coingecko.com/en/coins/babylons                                ",
    "https://www.coingecko.com/en/coins/wowswap                                 ",
    "https://www.coingecko.com/en/coins/the-parallel                            ",
    "https://www.coingecko.com/en/coins/verve                                   ",
    "https://www.coingecko.com/en/coins/shopnext                                ",
    "https://www.coingecko.com/en/coins/zuki-moba                               ",
    "https://www.coingecko.com/en/coins/dogewhale                               ",
    "https://www.coingecko.com/en/coins/metawars                                ",
    "https://www.coingecko.com/en/coins/portify                                 ",
    "https://www.coingecko.com/en/coins/moonscape                               ",
    "https://www.coingecko.com/en/coins/gyro                                    ",
    "https://www.coingecko.com/en/coins/monsta-infinite                         ",
    "https://www.coingecko.com/en/coins/empire-capital-token                    ",
    "https://www.coingecko.com/en/coins/wagyuswap                               ",
    "https://www.coingecko.com/en/coins/deblox                                  ",
    "https://www.coingecko.com/en/coins/dark-frontiers                          ",
    "https://www.coingecko.com/en/coins/shopperoo                               ",
    "https://www.coingecko.com/en/coins/peculium                                ",
    "https://www.coingecko.com/en/coins/belt                                    ",
    "https://www.coingecko.com/en/coins/wam                                     ",
    "https://www.coingecko.com/en/coins/bomb-money                              ",
    "https://www.coingecko.com/en/coins/fndz-token                              ",
    "https://www.coingecko.com/en/coins/sinverse                                ",
    "https://www.coingecko.com/en/coins/bscex                                   ",
    "https://www.coingecko.com/en/coins/green-climate-world                     ",
    "https://www.coingecko.com/en/coins/realfevr                                ",
    "https://www.coingecko.com/en/coins/froyo-games                             ",
    "https://www.coingecko.com/en/coins/bridge                                  ",
    "https://www.coingecko.com/en/coins/rich                                    ",
    "https://www.coingecko.com/en/coins/tendieswap                              ",
    "https://www.coingecko.com/en/coins/gamer                                   ",
    "https://www.coingecko.com/en/coins/deepspace                               ",
    "https://www.coingecko.com/en/coins/kalmar                                  ",
    "https://www.coingecko.com/en/coins/scallop                                 ",
    "https://www.coingecko.com/en/coins/warden                                  ",
    "https://www.coingecko.com/en/coins/bbs-network                             ",
    "https://www.coingecko.com/en/coins/annex-finance                           ",
    "https://www.coingecko.com/en/coins/faraland                                ",
    "https://www.coingecko.com/en/coins/shirtum                                 ",
    "https://www.coingecko.com/en/coins/julswap                                 ",
    "https://www.coingecko.com/en/coins/pacoca                                  ",
    "https://www.coingecko.com/en/coins/vcgamers                                ",
    "https://www.coingecko.com/en/coins/secret-finance                          ",
    "https://www.coingecko.com/en/coins/goose-finance                           ",
    "https://www.coingecko.com/en/coins/dehive                                  ",
    "https://www.coingecko.com/en/coins/rabbit-finance                          ",
    "https://www.coingecko.com/en/coins/nuke-token                              ",
    "https://www.coingecko.com/en/coins/inheritance-art                         ",
    "https://www.coingecko.com/en/coins/nolimitcoin                             ",
    "https://www.coingecko.com/en/coins/lepasa                                  ",
    "https://www.coingecko.com/en/coins/projectoasis                            ",
    "https://www.coingecko.com/en/coins/aetherv2                                ",
    "https://www.coingecko.com/en/coins/energyfi                                ",
    "https://www.coingecko.com/en/coins/dios-finance                            ",
    "https://www.coingecko.com/en/coins/swincoin                                ",
    "https://www.coingecko.com/en/coins/cashcow                                 ",
    "https://www.coingecko.com/en/coins/dfsocial-gaming                         ",
    "https://www.coingecko.com/en/coins/true-pnl                                ",
    "https://www.coingecko.com/en/coins/safutitano                              ",
    "https://www.coingecko.com/en/coins/plutos-network                          ",
    "https://www.coingecko.com/en/coins/canyacoin                               ",
    "https://www.coingecko.com/en/coins/cougar-token                            ",
    "https://www.coingecko.com/en/coins/imo                                     ",
    "https://www.coingecko.com/en/coins/chain-wars                              ",
    "https://www.coingecko.com/en/coins/aluna                                   ",
    "https://www.coingecko.com/en/coins/metafluence                             ",
    "https://www.coingecko.com/en/coins/moonpoly                                ",
    "https://www.coingecko.com/en/coins/bitorbit                                ",
    "https://www.coingecko.com/en/coins/wallstreetninja                         ",
    "https://www.coingecko.com/en/coins/airight                                 ",
    "https://www.coingecko.com/en/coins/media-eye                               ",
    "https://www.coingecko.com/en/coins/battle-pets                             ",
    "https://www.coingecko.com/en/coins/spacecowboy                             ",
    "https://www.coingecko.com/en/coins/merkle-network                          ",
    "https://www.coingecko.com/en/coins/aimedis                                 ",
    "https://www.coingecko.com/en/coins/inheritance-art                         ",
    "https://www.coingecko.com/en/coins/nolimitcoin                             ",
    "https://www.coingecko.com/en/coins/lepasa                                  ",
    "https://www.coingecko.com/en/coins/projectoasis                            ",
    "https://www.coingecko.com/en/coins/aetherv2                                ",
    "https://www.coingecko.com/en/coins/energyfi                                ",
    "https://www.coingecko.com/en/coins/dios-finance                            ",
    "https://www.coingecko.com/en/coins/symbull                                 ",
    "https://www.coingecko.com/en/coins/rasko                                   ",
    "https://www.coingecko.com/en/coins/seba                                    ",
    "https://www.coingecko.com/en/coins/bsc-station                             ",
    "https://www.coingecko.com/en/coins/angel-nodes                             ",
    "https://www.coingecko.com/en/coins/angel-nodes                             ",
    "https://www.coingecko.com/en/coins/impactmarket                            ",
    "https://www.coingecko.com/en/coins/coinmerge-bep20                         ",
    "https://www.coingecko.com/en/coins/everlens                                ",
    "https://www.coingecko.com/en/coins/tastenft                                ",
    "https://www.coingecko.com/en/coins/orclands-metaverse                      ",
    "https://www.coingecko.com/en/coins/horizon-protocol                        ",
    "https://www.coingecko.com/en/coins/demole                                  ",
    "https://www.coingecko.com/en/coins/veriblock                               ",
    "https://www.coingecko.com/en/coins/kaka-nft-world                          ",
    "https://www.coingecko.com/en/coins/projectx                                ",
    "https://www.coingecko.com/en/coins/sugarbounce                             ",
    "https://www.coingecko.com/en/coins/graphene                                ",
    "https://www.coingecko.com/en/coins/pera-finance                            ",
    "https://www.coingecko.com/en/coins/dyor                                    ",
    "https://www.coingecko.com/en/coins/dragon-kart-token                       ",
    "https://www.coingecko.com/en/coins/parex                                   ",
    "https://www.coingecko.com/en/coins/berry-data                              ",
    "https://www.coingecko.com/en/coins/crypto-fight-club                       ",
    "https://www.coingecko.com/en/coins/asia-coin                               ",
    "https://www.coingecko.com/en/coins/dough                                   ",
    "https://www.coingecko.com/en/coins/rise-of-defenders                       ",
    "https://www.coingecko.com/en/coins/dexsport                                ",
    "https://www.coingecko.com/en/coins/minersdefi                              ",
    "https://www.coingecko.com/en/coins/xmooney                                 ",
    "https://www.coingecko.com/en/coins/my-master-war                           ",
    "https://www.coingecko.com/en/coins/ftribe-fighters                         ",
    "https://www.coingecko.com/en/coins/trustfi-network-token                   ",
    "https://www.coingecko.com/en/coins/cryptoids-admin-coin                    ",
    "https://www.coingecko.com/en/coins/ghostmarket                             ",
    "https://www.coingecko.com/en/coins/less-network                            ",
    "https://www.coingecko.com/en/coins/nanobyte                                ",
    "https://www.coingecko.com/en/coins/alyattes                                ",
    "https://www.coingecko.com/en/coins/reward-hunters-token                    ",
    "https://www.coingecko.com/en/coins/market-ledger                           ",
    "https://www.coingecko.com/en/coins/starter-xyz                             ",
    "https://www.coingecko.com/en/coins/waultswap                               ",
    "https://www.coingecko.com/en/coins/cardence                                ",
    "https://www.coingecko.com/en/coins/lovelace-world                          ",
    "https://www.coingecko.com/en/coins/etna-network                            ",
    "https://www.coingecko.com/en/coins/elpis-battle                            ",
    "https://www.coingecko.com/en/coins/centric-swap                            ",
    "https://www.coingecko.com/en/coins/multiverse-capital                      ",
    "https://www.coingecko.com/en/coins/puli                                    ",
    "https://www.coingecko.com/en/coins/cryptozoon                              ",
    "https://www.coingecko.com/en/coins/treatdao                                ",
    "https://www.coingecko.com/en/coins/catbonk                                 ",
    "https://www.coingecko.com/en/coins/warena                                  ",
    "https://www.coingecko.com/en/coins/coinary-token                           ",
    "https://www.coingecko.com/en/coins/xp-network                              ",
    "https://www.coingecko.com/en/coins/decubate                                ",
    "https://www.coingecko.com/en/coins/rune                                    ",
    "https://www.coingecko.com/en/coins/evereth                                 ",
    "https://www.coingecko.com/en/coins/zeptacoin                               ",
    "https://www.coingecko.com/en/coins/cogiverse                               ",
    "https://www.coingecko.com/en/coins/luna-rush                               ",
    "https://www.coingecko.com/en/coins/meme-lordz                              ",
    "https://www.coingecko.com/en/coins/superlauncher-dao                       ",
    "https://www.coingecko.com/en/coins/leon-token                              ",
    "https://www.coingecko.com/en/coins/gunstar-metaverse                       ",
    "https://www.coingecko.com/en/coins/mmocoin                                 ",
    "https://www.coingecko.com/en/coins/ditto                                   ",
    "https://www.coingecko.com/en/coins/bishares                                ",
    "https://www.coingecko.com/en/coins/eleven-finance                          ",
    "https://www.coingecko.com/en/coins/gunstar-metaverse-currency              ",
    "https://www.coingecko.com/en/coins/squirrel-finance                        ",
    "https://www.coingecko.com/en/coins/hashtagger                              ",
    "https://www.coingecko.com/en/coins/zionomics                               ",
    "https://www.coingecko.com/en/coins/crystal-kingdoms                        ",
    "https://www.coingecko.com/en/coins/monster-slayer-share                    ",
    "https://www.coingecko.com/en/coins/trickle                                 ",
    "https://www.coingecko.com/en/coins/multiplier-bsc                          ",
    "https://www.coingecko.com/en/coins/bearn-fi                                ",
    "https://www.coingecko.com/en/coins/taichi                                  ",
    "https://www.coingecko.com/en/coins/llamaswap                               ",
    "https://www.coingecko.com/en/coins/kalissa                                 ",
    "https://www.coingecko.com/en/coins/shining-crystal-shard                   ",
    "https://www.coingecko.com/en/coins/the-lab-finance                         ",
    "https://www.coingecko.com/en/coins/duet-protocol                           ",
    "https://www.coingecko.com/en/coins/spacegrime-x                            ",
    "https://www.coingecko.com/en/coins/bitcrush                                ",
    "https://www.coingecko.com/en/coins/xanalia                                 ",
    "https://www.coingecko.com/en/coins/bytenext                                ",
    "https://www.coingecko.com/en/coins/crow                                    ",
    "https://www.coingecko.com/en/coins/moonlight-token                         ",
    "https://www.coingecko.com/en/coins/anime-token                             ",
    "https://www.coingecko.com/en/coins/linear-bsc                              ",
    "https://www.coingecko.com/en/coins/psychic                                 ",
    "https://www.coingecko.com/en/coins/macaronswap                             ",
    "https://www.coingecko.com/en/coins/investdex                               ",
    "https://www.coingecko.com/en/coins/depocket                                ",
    "https://www.coingecko.com/en/coins/teneo                                   ",
    "https://www.coingecko.com/en/coins/localtrade                              ",
    "https://www.coingecko.com/en/coins/mercor-finance                          ",
    "https://www.coingecko.com/en/coins/hnk-orijent-1919-token                  ",
    "https://www.coingecko.com/en/coins/robust-token                            ",
    "https://www.coingecko.com/en/coins/checkdot                                ",
    "https://www.coingecko.com/en/coins/graviton-zero                           ",
    "https://www.coingecko.com/en/coins/nemesis-dao                             ",
    "https://www.coingecko.com/en/coins/ghospers-game                           ",
    "https://www.coingecko.com/en/coins/crypto-birds                            ",
    "https://www.coingecko.com/en/coins/socialx                                 ",
    "https://www.coingecko.com/en/coins/dungeonswap                             ",
    "https://www.coingecko.com/en/coins/pancake-bunny                           ",
    "https://www.coingecko.com/en/coins/midas-dollar                            ",
    "https://www.coingecko.com/en/coins/jetoken                                 ",
    "https://www.coingecko.com/en/coins/crypto-development-services             ",
    "https://www.coingecko.com/en/coins/fungie-dao                              ",
    "https://www.coingecko.com/en/coins/porta                                   ",
    "https://www.coingecko.com/en/coins/operon-origins                          ",
    "https://www.coingecko.com/en/coins/bscwin-bulls                            ",
    "https://www.coingecko.com/en/coins/soccerhub                               ",
    "https://www.coingecko.com/en/coins/nftmall                                 ",
    "https://www.coingecko.com/en/coins/staysafu                                ",
    "https://www.coingecko.com/en/coins/golden-ball                             ",
    "https://www.coingecko.com/en/coins/world-of-defish                         ",
    "https://www.coingecko.com/en/coins/battle-saga                             ",
    "https://www.coingecko.com/en/coins/bunnypark-game                          ",
    "https://www.coingecko.com/en/coins/value-finance                           ",
    "https://www.coingecko.com/en/coins/moonfarm-finance                        ",
    "https://www.coingecko.com/en/coins/obtoken                                 ",


];

$slack = new SlackClient('https://hooks.slack.com/services/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');;

$crawler = new Crawler();

$lastRoundCoins = unserialize(file_get_contents('last_rounded_coins.txt'));
if (empty($lastRoundCoins)) {
    $lastRoundCoins = [];
}

$alertCoins = Crawler::removeDuplicates($crawler->returnArray, $lastRoundCoins);

shuffle($list);
foreach ($list as $coin) {

    try {
        $percent = (float)$crawler->assignDetailInformationToCoin($coin);
        if ($percent > 20.00) {
            $message = new Message();
            $message->setText($coin);
            $slack->sendMessage($message);
            $crawler->returnArray[] = trim($coin);
        }
    } catch (Exception $e) {
        $crawler->getClient()->quit();
        continue;
    }
}
$crawler->getClient()->quit();



file_put_contents('last_rounded_coins.txt', serialize($crawler->returnArray));

